# Generated by Django 4.2 on 2023-07-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='chatter/static/chatter/profile_picture'),
        ),
    ]
