# Generated by Django 4.2 on 2023-07-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0004_remove_user_image_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group_count',
        ),
    ]
