# Generated by Django 4.2 on 2023-07-24 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0005_remove_user_friend_count_remove_user_group_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_1', to=settings.AUTH_USER_MODEL)),
                ('friend_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.CharField(blank=True, max_length=1000)),
                ('direct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='chatter.direct')),
                ('likes', models.ManyToManyField(related_name='likes_direct', to=settings.AUTH_USER_MODEL)),
                ('messager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_direct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
