# Generated by Django 4.2 on 2023-07-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter', '0007_group_groupmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(default='General', max_length=1000),
        ),
    ]
